from custom_types.custom_download_location_configuration import CustomDownloadLocationConfiguration
from custom_types.download_behavior_configuration import DownloadBehaviorConfiguration
from custom_types.download_configuration import DownloadConfiguration
from custom_types.quality_of_life_configuration import QualityOfLifeConfiguration
from custom_types.warning_configuration import WarningConfiguration
from custom_types.configuration import Configuration